- Parser/sensusUltraParse.m
Uninitialized fields sample_data.dimensions and sample_data.variables cause Matlab (tested on R2014a) to throw an error, and hence the data file will not be imported.
> Initialize missing fields in sensusUltraParse.m

- NetCDF/templateType.m
The BufSize option to textscan has been obsoleted in R2015b. As this function is reading in relatively small template files it should not be necessary for performance and so can be removed for all Matlab versions.
> textscan BufSize option has been obsoleted

- FlowManager/flowManager.m
- Preprocessing/CTDDepthBinPP.m
- Preprocessing/aquatrackaPP.m
- Preprocessing/binMappingVelocityPP.m
- Preprocessing/depthPP.m
- Preprocessing/magneticDeclinationPP.m
- Preprocessing/pressureRelPP.m
- Preprocessing/rdiBinMappingVelocityPP.m
- Preprocessing/rinkoDoPP.m
- Preprocessing/salinityPP.m
- Preprocessing/soakStatusPP.m
- Preprocessing/timeMetaOffsetPP.m
- Preprocessing/timeOffsetPP.m
- Preprocessing/timeStartPP.m
- Preprocessing/transformPP.m
- Preprocessing/variableOffsetPP.m
Originally submitted by @BecCowley :
Change FlowManager to use rawData (instead of nonUTCRawData) when applying any time PP routines to create autoQCData structure. This means that the time PP routines that are applied to the rawData are carried through to autoQCData. Previously, the timeOffsetPP routine reset the offsets to zero when run the second time.
Supersedes https://github.com/aodn/imos-toolbox/pull/266
> Flow manager fix

- Graph/TimeSeries/flagTimeSeriesGeneric.m
- Graph/TimeSeries/flagTimeSeriesTimeDepth.m
- Graph/TimeSeries/flagTimeSeriesTimeFrequency.m
- Graph/TimeSeries/getSelectedTimeSeriesGeneric.m
- Graph/TimeSeries/getSelectedTimeSeriesTimeDepth.m
- Graph/TimeSeries/getSelectedTimeSeriesTimeFrequency.m
- Graph/TimeSeries/graphTimeSeriesGeneric.m
- Graph/TimeSeries/graphTimeSeriesTimeDepth.m
- Graph/TimeSeries/graphTimeSeriesTimeFrequency.m
- Graph/TimeSeries/graphTimeSeriesTimeFrequencyDirection.m
Some of the graphing routines are grabbing the TIME dimension id directly from the variables dimension layout, is there a reason for this? Assuming there isn't below set of patches uses the standard getVar(sample_data.dimensions, 'TIME') syntax.
If this is ok, then there are cases of routines looking for frequency or direction related dimension eg flagTimeSeriesTimeFrequency.m that could be updated in a similar fashion.
> Remove hardwired TIME dimension id access.

- Parser/readParadoppBinary.m
Most of the time:
-battery and analog inputs are uint16,
-temperature is int16 (and can now support negative values...),
-status and error are int8 (error can sometimes be int16).
Checksum is left uint16 (although defined int16) because of how the check is implemented in Matlab. Retrieved value doesn't matter much, what matters is that the check finds consistent values.
> Fix paradopp

- FlowManager/displayManager.m
- GUI/mainWindow.m
Work around for Matlab >= R2018b where zoom/pan etc buttons no longer live on figure toolbar. Reference https://www.mathworks.com/matlabcentral/answers/419036-what-happened-to-the-figure-toolbar-in-r2018b-why-is-it-an-axes-toolbar-how-can-i-put-the-buttons
Would be nice is someone else confirms it works on there setup.
> Work around for Matlab >= R2018b zoom/pan etc buttons, closes #551

- build.py
This is a new build script for the stand-alone version for discussion.
Advantages:
- No matlab calls, except mcc.
- better capabilities: specify the MCCRoot, repo folder, binary output folder and the architecture.
- improve binary names to include current repository state (good for debugging, verification, sharing binaries, etc).
- write auxiliar version number to .standalone_canonical_version (standalone requirements)
The script includes the same logic/capability mentioned in #568, but it's not the entire solution. Some logic is still required in the toolbox for stand-alone and the non-binary usages. However, the idea is here - replicate the get_info method - and set the version code accordingly - this is discussed further in #568.
To discuss:
- Should we keep maintaining the binary …
> [WIP] include new python build script

- Parser/infinitySDLoggerParse.m
- Util/TimeSamplingInfo.m
- Util/find_repeats.m
- Util/fixRepeatedTimesJFE.m
- Util/isunique.m
- test/Util/testTimeSamplingInfo.m
- test/testRepeatedTimesJFE.m
This fixes the problem with InfinitySD not outputing the miliseconds of burst measurements.
> Infinity timefix, closes #536

- get_testfiles.py
- send_testfile.sh
The test data can be reached by several tools,
but in the case a user doesn't know the tools
a script in python is provided to get the files.
Only authorized POs can send data, so I'm keeping
a simple send script in the shell for simplicity and to
allow easy parallelisation.
> tools to get/send testfiles to imos-toolbox bucket

- Parser/infinitySDLoggerParse.m
- test/Util/testtimeSamplingInfo.m
- test/testRepeatedTimesJFE.m
I clearly missed running the tests before submitting
> #598.
This complete the renames of the function in the parser, test functions and
also corrected the path of the test file.
> quickfix: missing renames of timeSamplingInfo function

- Preprocessing/aquatrackaPP.m
This commit remove previous warning message and put
a simple logic handler for multi vars in the
aquatracka pre-processing function.
The multi-var case should be quite rare but happens
during tests since we create fake voltage variables in
structures with CPHL data already.
> feat(Preprocessing): allow multi var names in aquatrackapp

- Util/CellUtils/inCellPartialMatch.m
- Util/CellUtils/popFromCell.m
- test/Util/CellUtils/testPopFromCell.m
- test/Util/CellUtils/test_inCellPartialMatch.m
The gist of this PR is to 1.fix a broken function ```popfromcell``` and 2. fix an incorrect case handling of an empty match within ```inCellPartialMatch```.
The problems were not picked because the tests were manual and not ported away from the respective examples docstrings. Hence, I also 3. update docstrings and 4. included the proper tests files.
Finally, the files were previously merged using the non-standard linting scheme/config, so I also 5. adjusted the affected files to the "standard toolbox linting" scheme.
Hence, the commits with linting scope should be ignored, since they affect all lines and are just space adjustments.
> Cellutils fixes

- get_testfiles.py
The changes allow users without AWS credentials
to run get_testfiles.py. 
This passed under my radar since I got aws
credentials already configured.
> bug(tests): fix credentials in get_testfiles.py

- Parser/StarmonDSTParse.m
- Parser/StarmonMiniParse.m
This is a requirement for transparent usage of the
new Staroddi Parser that supports Mini v0, Mini v1, DST Tilt
and DST CTD.
The reason why is done this way is to still support
old insturments.txt configuration files, database
key:value associations, and to be transparent to the user.
> feat(Parsers): Re-use old parser names to new parser, closes #622 #549

- IMOS/genIMOSFileName.m
This move the filename conventions to use the ```time_deployment``` fields isntead of ```time_coverage``` fields.
@ggalibert , please check if this is what you had in mind in #541
> Filenames with deployment field, closes #541

- Parser/GenericParser/InstrumentParsers/StaroddiParser.m
- test/Parser/testStaroddi.m
Fixes the Star oddi tests that compares old and new parsers
data on arbitrary machines.
The original path of a file is stored as string in
a structure so it will never match a dynamical file loading.
The filenames should be the same though.
> feat(tests): compare filename instead of filepath

- AutomaticQC/imosTimeSeriesSpikeQC.m
fix #676 by filtering 2d variables in load_timeseries_variables,
which should only select vector variables.
> feat(bugfix): filter 2d variables in SpikeQC

- AutomaticQC/imosTiltVelocitySetQC.m
- test/AutomaticQC/test_imosTiltVelocitySetQC.m
When adding support to current meters in TiltQC,
I implemented wrong assignment logic to the flags
that broke ADCP processing (multi dimensional flags).
The problem was not picked up by adcp testing because
those tests were also wrongly based on current meter templates,
and the pitch/roll dimensions were wrongly assigned and bypassed
proper evaluations.
> feat(bugfix): correct ADCP tilt flag broadcasting, fixes #680

- GUI/instrumentAliases.txt
- Preprocessing/depthPP.m
- Util/genSampleDataDesc.m
- Util/readMappings.m
- toolboxProperties.txt
These changes permit the user to set
the level of detail shown on all UI elements related
to instrument metadata description.
Two new options are provided in the toolboxProperties,
`instrumentAliases` and `detailLevel`.
instrumentAliases modify the display name of instruments
in the UI to the entries presented within
the GUI/instrumentAliases.txt file.
detailLevel modify the data description in all UI elements
to match several named options.
See the updated toolboxProperties.txt file for details.
> feat(UI): detailLevel and aliases for instruments

- Graph/checkMooringPlannedDepths.m
- Util/select_points.m
This fix a distribution/compatibility problem
related to the drawrectangle function which is
exclusive of the image processing toolbox.
The fix provide a fallback to the old functionality
in the case the toolbox is not installed/available.
@BecCowley
> fix(graph): fallback for missing the image toolbox

- Util/azimuth_direction.m
This fixes another runtime compatibility issue. See commit msgs.
During manual testing, I clearly forgot to test with an RDI file in ENU coordinates with the most recently build binaries.
> Fix missing runtime

- imosToolbox.m
both code and binaries landed without a release version bump. This is the 4th time this happeneed so I think it is time to implement some bump version mechanism.
> fix: hot-fix release version bump

- build.py
This is a very low priority PR - it just fixes an argument parsing for the matlab path. We handle most of the paths automatic now and this flag is highly optional and only used for very unusual Matlab paths.
> fix: build --matlab_path argument parsing, fixes 

- AutomaticQC/imosErrorVelocitySetQC.m
Originally submitted by @BecCowley :
> Should have an & to find error velocity values that are between the two extremes.
Supersedes #756
> (Fix) Error velocity QC should be & not |

- Preprocessing/+NortekADCP/adcp_adjusted_distances_nortek3beam.m
- Preprocessing/+TeledyneADCP/adcp_adjusted_distances_rdi4beam.m
- Preprocessing/adcpBinMappingPP.m
Originally submitted by @BecCowley
Supersedes https://github.com/aodn/imos-toolbox/pull/755
> This fix is a sign adjustment to the bin mapping algorithm based on the direction the instrument is facing. Current code is only correct for up-facing ADCPs.
Also adds the pitch gimbal correction.
@BecCowley , I resubmitted your PR to only include the relevant commits. Note that I divided one of your commit in 2 (`Add pitch adjustment calculation` and `add upward looking definitions`). I also added a clarification in the comments describing the orientation of the RDI 4 beams ADCPs, let me know if you're happy with that:
> For an upward looking ADCP, when pitch is positive beam 3 is closer to the surface while beam 4 gets further away. When roll is positive beam 2 is closer to the surface while …
> Bug binmapping

- AutomaticQC/imosSideLobeVelocitySetQC.m
The link in this script is not working anymore. Instead, it'll be best to point to the wiki so there is only one place holder to update when we need to update.
I'm just about to update the [wiki for the corresponding section](https://github.com/aodn/imos-toolbox/wiki/QCProcedures#adcp-side-lobe-contamination-test---imossidelobevelocitysetqc---compulsory)
> docs: remove old link and add link to wiki

- Parser/OceanContour/OceanContour.m
- Util/+IMOS/+resolve/imos_type.m
- Util/+IMOS/+resolve/is_numbered_var.m
- Util/+IMOS/+templates/dimensions.m
- Util/+IMOS/gen_dimensions.m
- Util/+IMOS/gen_variables.m
- test/Parser/GenericParser/testOceanContour.m
@ocehugo added commits to your og PR https://github.com/aodn/imos-toolbox/pull/788 which can be closed.
The tests files used by the unittest need to be uploaded to the imos-toobox bucket, which I'll do once merged.
However I dug a bit in the sample files provided and had a bit of a concern.
The s500 sample file provided (s500_enu_avg.nc) seems to have a fillvalue of
-32.7680 for the UCUR variable 
The s1000 sample file (Avg_001.VTC.nc) on the other hand seems to have a
fillvalue of -3.27680
If exported as a NetCDF, one can see that the valid_min and valid_max values for
the UCUR variable are respectively -10 and 10.
So the repeated value of -3.27680 for the S1000 sample file ends up being in the
valid range, but I believe it should be a FillValue.
Is there a reason why the s500 and s1000 …
> Ocean contour updates

- AutomaticQC/imosTimeSeriesSpikeQC.m
- GUI/spikeWindow.m
- IMOS/finaliseData.m
- Util/genSampleDataDesc.m
This necessitated copying the meta struct which contains make/model info. Use genSampleDataDesc to create instrument string instead of concatenating make/model info. Final instrument info string is display above the uipanel.
> Add instrument info text string to spikeWindow GUI

- Parser/readAD2CPBinary.m
- test/Parser/testSignature.m
* the previous version of the parser could not possibly work. variable names
were not always used properly
* amend the index values to read various Nortek variables to match the Nortek 2022 manual
* add unittest with bottom tracking provided by Clark Richards
> Fix(readAD2CPBinary): various issues with Bottom tracking parser
