Parser/readParadoppBinary.m
- fix readAwacAST offset calculation
- fix length calculation for readWaveFourierCoefficentSpectrum, readWaveBandEstimates and readWaveParameterEstimates
=> fix some offset and length calculations

Parser/readParadoppBinary.m
Read in structures
Id54 readAwacWaveDataSUV % 0x36
Id66 readAwacStageData % 0x42
Id96 readWaveParameterEstimates % 0x60
Id97 readWaveBandEstimates % 0x61
Id98 readWaveEnergySpectrum % 0x62
Id99 readWaveFourierCoefficentSpectrum % 0x63
Modify readParadoppBinary to correctly handle some special Id's with variable size fields, currently only two (Id66 and Id98).
Standardize field names, some where from C struct names which didn't match the style of the rest of the code.
The only structures not handled are
Id34 (0x22) 2-beam aquadopp
Id35 (0x23) 1-beam aquadopp
Id37 (0x25) 2-beam continental
Id38 (0x26) 1-beam continental
Id7 (0x07) vector probe check
To be confirmed of Id96-Id99 : Data that is determined to be invalid in the wave processing is flagged with a hex value of 0xFFFF. This means …
=> Handle most raw Nortek  binary structures and more processed Storm structures

Parser/readWorkhorseEnsembles.m
ADC channels are sequentially sampled per ping, nan channels not sampled in that ensemble. For example, if the ping group size is 5, then:
END OF ENSEMBLE No.   CHANNELS UPDATED
Start                 All channels = 0
1                     0, 1, 2, 3, 4
2                     5, 6, 7, 0, 1
Further description of ADC channels in "WORKHORSE COMMANDS AND OUTPUT DATA FORMAT (March 2014)" document, pg 134, 136-137.
=> NaN ADC channels not sampled at that ensemble.

Parser/readWQMraw.m
These are the fixes done on top of PR #555. I had to implement some extras.
I had to refactor since the scope was a bit messy. I think I left the code in better shape.
The PR can generate the structures for all files within the test folder and runTests.m got a pass.
=> Sspagnol wqm missingvar, closes #557

Parser/readWQMraw.m
Had a case of a very badly behaved WQM which didn't record one of it's primary variables (press in my case). So just a simple check that cond/pres/temperature aren't empty. But it does have flow on effects for calculation of salinity and oxygen.
Wondering if same test should also be done for oxygen and O2cal depend on ~noSainity || ~noOxygen?
Have coded missing variable logic as (eg) noTemperature is true if no temperature, but you may wish to rewrite as hasTemperature is true if have temperature.
=> Handle case of WQM which didn't record one of it's primary variables

Parser/convertSBEcnvVar.m
Please see discussion in #550. 
This should require a proper test but the codebase is not ready yet for this
=> support flCUVA+PAR in SBE19Plus cnv, closes #550

Util/Schema/createTree.m, Util/Schema/detectCellContent.m, Util/Schema/detectStructContent.m, Util/Schema/detectType.m, Util/Schema/isdouble.m, Util/Schema/isequal_ctype.m, Util/Schema/isfunctionhandle.m, Util/Schema/isint16.m, Util/Schema/isint32.m, Util/Schema/isint64.m, Util/Schema/isint8.m, Util/Schema/issingle.m, Util/Schema/isuint16.m, Util/Schema/isuint32.m, Util/Schema/isuint64.m, Util/Schema/isuint8.m, Util/Schema/objinfo.m, Util/Schema/treeDiff.m, Util/Schema/validate.m, Util/Schema/validateType.m, Util/Schema/whichtype.m, test/testSchema.m
This PR includes a schema validation utility.
It's included here as the primary tool for me (and hopefully others) to develop the toolbox with further confidence and provide enhanced checking when comparing and ensuring the data structures are what they should be.
This PR is self-contained and do not depend on anything related to the toolbox - only Matlab standard routines.
=> schema validation for most matlab types, closes #577

Util/CellUtils/cell2str.m, Util/CellUtils/fillEmptyCellIndex.m, Util/CellUtils/inCell.m, Util/CellUtils/inCellPartialMatch.m, Util/CellUtils/isAnyCellItemEmpty.m, Util/CellUtils/joinCell.m, Util/CellUtils/popFromCell.m, Util/CellUtils/whereincell.m, Util/swarning.m
This is required for Schema testing and Generic
Header/Data readers.
=> import of cellUtils funcs

Util/StructUtils/combineStructFields.m, Util/StructUtils/fields2cell.m
This is a req. for the generic readers.
=> include StructUtils functions

Util/findRepeats.m, Util/fixRepeatedTimesJFE.m, Util/timeSamplingInfo.m
This include renames proposed in #594
=> files and function calls renaming in affected code

imosToolbox.m
=> fix: bump version string, closes #605

Util/Path/basename.m
A function that mimic the gnu coreutils basename function
=> feat(path): include a basename function

Parser/GenericParser/DataParser.m, Parser/GenericParser/HeaderParser.m, Parser/GenericParser/InstrumentParsers/StaroddiParser.m, Parser/GenericParser/InstrumentRules/StaroddiRules.m, Parser/GenericParser/argstruct.m, Parser/GenericParser/detectEncoding.m, Parser/GenericParser/mapDataNames.m, Parser/GenericParser/readHeaderDict.m, Parser/GenericParser/readLinesWithRegex.m, Parser/GenericParser/translateHeaderText.m, Parser/signatureParse.m, Util/Path/basename.m, Util/convertVariables.m, Util/getIMOSType.m, Util/isnumbered.m, Util/loadTimeSeriesSampleTemplate.m, Util/resolveIMOSName.m, Util/resolveString.m, Util/units/toCelsius.m, test/Parser/testSignature.m, test/Parser/testStaroddi.m, test/testStaroddi.m
=> Nortek signature fixes, closes #554

get_testfiles.py
reduce complexity & allow the script to run even when AWS environmental variable are invalid.
=> Fix get testfiles

Parser/GenericParser/InstrumentRules/StaroddiRules.m
This fixes #633 and close for good #549
=> Staroddi date enhancement, closes #549, closes #633

Parser/netcdfParse.m, test/Parser/testnetcdfParse.m
=> Netcdf parser fixes, closes #644

AutomaticQC/SpikeClassifiers/imosSpikeClassifierBurstHampel.m, AutomaticQC/SpikeClassifiers/imosSpikeClassifierBurstRunningStats.m, AutomaticQC/SpikeClassifiers/imosSpikeClassifierHampel.m, AutomaticQC/SpikeClassifiers/imosSpikeClassifierNonBurstSavGolOTSU.m, AutomaticQC/SpikeClassifiers/imosSpikeClassifierOTSU.m, AutomaticQC/SpikeClassifiers/imosSpikeClassifierRunningStats.m, AutomaticQC/SpikeClassifiers/imosSpikeClassifiersLimits.m, AutomaticQC/SpikeClassifiers/loadSpikeClassifiers.m, AutomaticQC/SpikeClassifiers/otsu_threshold.m, AutomaticQC/imosTimeSeriesSpikeQC.m, AutomaticQC/imosTimeSeriesSpikeQC.txt, AutomaticQC/imosTimeSeriesSpikeQCBurst.txt, AutomaticQC/qcFilterMain.m, GUI/previewWindow.m, GUI/spikeWindow.m, Util/QC/validBounds.m, Util/Schema/isint.m, Util/Time/findBursts.m, Util/Time/nextLowerTimePrecision.m, Util/Time/precisionBounds.m, Util/UI/numericInputButton.m, Util/getSampleField.m, test/AutomaticQC/test_SpikeClassifiers.m, test/UI/test_spikePreview.m
=> SpikeQC Burst Spike functionality, Preview, and small fixes

NetCDF/template/global_attributes_profile.txt, NetCDF/template/global_attributes_timeSeries.txt
=> feat(metadata): update acknowledgement in template

AutomaticQC/imosTimeSeriesSpikeQC.m, AutomaticQC/imosTimeSeriesSpikeQC.txt, AutomaticQC/imosTimeSeriesSpikeQCBurst.txt, test/UI/test_imosTimeSeriesSpikeQC.m
=> fixup for 676, fixes 676

build.py
This commit cleans up the file gathering
and handling to the matlab compiler within the
build python script.
A more selective filtering is done now instead
of including all files (recursively) of the
repository. This removes some warnings, like
when importing toolbox package
folders (e.g.`+IMOS`), remove unused files
and datasets (e.g. `snapshot` & `dist`).
=> fix(build): toolbox package folders & cleanup

Parser/workhorseParse.m
last minute for the new hot-fix.
=> Fix magdec wave name workhorse, fixes #743

Graph/adcpEnsemblesThresholds.m, Graph/adcpScreeningThresholds.m, Graph/adcpThresholds.m, Graph/adcpThresholdsResults.m, test/single_pingADCPtest.m
Updates to the screening threshold plotting scripts.
Originally submitted by @BecCowley 
Supersedes #769
=> feat(graph): update ADCP thresholds plots

imosToolbox.m
@leonardolaiolo let's have a quick chat before merging
=> release:2.6.16
